### ISSUE TITLE
Broken Link (404) in Reserved Words > LEN

### ISSUE THREAD

**Issue by LamptonWorm** [boriel-basic/docs#9]
Via https://zxbasic.readthedocs.io/en/docs/identifier/
https://zxbasic.readthedocs.io/en/docs/identifier/len.md is broken

**Comment by boriel** [comment]
Note that this is due to the `/docs/` path. It should be `/latest/` or a version.
It exists in https://zxbasic.readthedocs.io/en/latest/len/  (I will disable the `docs/` version).
